apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fortune-cookie-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - fortune-cookie.orbithr.com.br
    secretName: cloudflare-origin-cert
  rules:
  - host: fortune-cookie.orbithr.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
